### PR TITLE
Resolve #670: bug: timestamppb conversion at connection state

### LINKED ISSUE #670: bug: timestamppb conversion at connection state
Image

### PR DESCRIPTION
**Pull request by SazukinPavel**

### CODE REVIEW

**Review by vladimirnikolic509 — APPROVED** [review]

File: console/src/components/devices/device_card/status-corner.vue [hunk 1]
```diff
@@ -34,8 +34,9 @@ function render() {
 
     if (props.connection) {
         status = props.connection.connected ? 'online' : 'offline'
-        if (props.connection.timestamp) {
-            let d = new Date(props.connection.timestamp)
+        const timestamp = props.connection.timestamp?.toDate() || props.connection.timestamp
+        if (timestamp) {
```
Comment (slntopp) [inline console/src/components/devices/device_card/status-corner.vue:38]: Useless condition, since you have `.? ||` clause, timestamp will always be not `null`

File: console/src/components/devices/device_card/status-corner.vue [hunk 2]
```diff
@@ -34,8 +34,9 @@ function render() {
...
+            let d = new Date(timestamp)
```
Comment (slntopp) [inline console/src/components/devices/device_card/status-corner.vue:39]: Since you're using `toDate()` method above - useless type casting

**Review by slntopp — CHANGES_REQUESTED** [review]

File: console/src/components/devices/device_card/status-corner.vue (hunk 2 above)
Comment (SazukinPavel) [reply console/src/components/devices/device_card/status-corner.vue:39]: i expect timestamp as number or rpc  Timestamp type. number requires casting. and also props.connection.timestamp can be null, so so this expression also will be wrong:
props.connection.timestamp?.toDate() || new Date(props.connection.timestamp) 

so I don't see a better option than this

File: console/src/components/devices/device_card/status-corner.vue (hunk 1 above)
Comment (SazukinPavel) [reply console/src/components/devices/device_card/status-corner.vue:38]: timestamp may be null. at least for now, so this check makes sense

**Review by slntopp — APPROVED** [review]
